<a href="https://colab.research.google.com/github/CharitarthAntala/Machine-Learning-Practical/blob/main/numpy_methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 78 ,45 ,85])
str = np.array(['hello world'])

newarr = arr.reshape(4, 4)

print("\nreshape():\n",newarr)


reshape():
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [15 78 45 85]]


In [ ]:
print("\nravel():\n", newarr.ravel())


ravel():
 [ 1  2  3  4  5  6  7  8  9 10 11 12 15 78 45 85]


In [ ]:
print("\nflatten():\n", newarr.flatten())


flatten():
 [ 1  2  3  4  5  6  7  8  9 10 11 12 15 78 45 85]


In [ ]:
movAxis = np.moveaxis(newarr, 0, -1)
print("\nmoveaxis():\n", movAxis)


moveaxis():
 [[ 1  5  9 15]
 [ 2  6 10 78]
 [ 3  7 11 45]
 [ 4  8 12 85]]


In [ ]:
print("\nroll():\n", np.roll(newarr, 1))


roll():
 [[85  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 15 78 45]]


In [ ]:
print("\ntranspose():\n", newarr.transpose())


transpose():
 [[ 1  5  9 15]
 [ 2  6 10 78]
 [ 3  7 11 45]
 [ 4  8 12 85]]


In [ ]:
splitArr = np.array_split(arr, 3)
print("\nsplit():\n",splitArr)


split():
 [array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11]), array([12, 15, 78, 45, 85])]


In [ ]:
dsplit =arr.reshape (2,2,4)
print("\ndplit():\n",np.dsplit(dsplit,4))


dplit():
 [array([[[ 1],
        [ 5]],

       [[ 9],
        [15]]]), array([[[ 2],
        [ 6]],

       [[10],
        [78]]]), array([[[ 3],
        [ 7]],

       [[11],
        [45]]]), array([[[ 4],
        [ 8]],

       [[12],
        [85]]])]


In [ ]:
print("\nhplit():\n",np.hsplit(dsplit,2))


hplit():
 [array([[[ 1,  2,  3,  4]],

       [[ 9, 10, 11, 12]]]), array([[[ 5,  6,  7,  8]],

       [[15, 78, 45, 85]]])]


In [ ]:
print("\nvplit():\n",np.vsplit(dsplit,2))


vplit():
 [array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]]), array([[[ 9, 10, 11, 12],
        [15, 78, 45, 85]]])]


In [ ]:
print("\ninsert():\n",np.insert(arr, 1, 9))


insert():
 [ 1  9  2  3  4  5  6  7  8  9 10 11 12 15 78 45 85]


In [ ]:
print("\ndelete():\n",np.delete(arr, 9))


delete():
 [ 1  2  3  4  5  6  7  8  9 11 12 15 78 45 85]


In [ ]:
print("\nappend():\n",np.append(arr, str))


append():
 ['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '15' '78' '45' '85'
 'hello world']


In [ ]:
uniq = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,9,9, 10, 11, 12, 15, 78 ,45 ,85])
print("\nunique():\n",np.unique(arr))


unique():
 [ 1  2  3  4  5  6  7  8  9 10 11 12 15 45 78 85]


In [ ]:
print("\nflip():\n",np.flip(newarr, 0))


flip():
 [[15 78 45 85]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
print("\nfliplr():\n",np.fliplr(newarr))


fliplr():
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [85 45 78 15]]


In [ ]:
print("\nfliplr():\n",np.flipud(newarr))


fliplr():
 [[15 78 45 85]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
print("\nrot90():\n",np.rot90(newarr))


rot90():
 [[ 4  8 12 85]
 [ 3  7 11 45]
 [ 2  6 10 78]
 [ 1  5  9 15]]


In [ ]:
file1 = open("BE SEM 7 ML/files/file.txt","r")
fileData = file1.read()
occurrences = fileData.count("hello")
print(occurrences)